package com.example.kolla.enums;

public enum ActionLog {
    REGISTER, LOGIN, UPDATE_INFO, CREATE_USER, DELETE_USER, UPDATE_AVATAR, CHANGE_PASSWORD,
    CREATE_MEETING, UPDATE_MEETING, DELETE_MEETING, CREATE_DEPARTMENT, UPDATE_DEPARTMENT, DELETE_DEPARTMENT,
    CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE, CREATE_USER_SESSION, DELETE_USER_SESSION,
    CREATE_MEETING_MEMBER, DELETE_MEETING_MEMBER, CREATE_MEETING_INVITATION, DELETE_MEETING_INVITATION,
    CREATE_MEETING_INVITATION_RESPONSE, DELETE_MEETING_INVITATION_RESPONSE,
    CREATE_MEETING_INVITATION_RESPONSE_MESSAGE, DELETE_MEETING_INVITATION_RESPONSE_MESSAGE,
    CREATE_MEETING_INVITATION_RESPONSE_MESSAGE_REACTION, DELETE_MEETING_INVITATION_RESPONSE_MESSAGE_REACTION,
    CREATE_MEETING_INVITATION_RESPONSE_MESSAGE_REACTION_REACTION, DELETE_MEETING_INVITATION_RESPONSE_MESSAGE_REACTION_REACTION,
    CREATE_MEETING_INVITATION_RESPONSE_MESSAGE_REACTION_REACTION_REACTION, DELETE_MEETING_INVITATION_RESPONSE_MESSAGE_REACTION_REACTION_REACTION
}
